subscription_id = "<SUBSCRIPTION_ID>"
client_id       = "<CLIENT_ID>"
client_secret   = "<CLIENT_SECRET>"
tenant_id       = "<TENANT_ID>"
rg_prefix       = "terraform-ws"
rg_location     = "West Europe"
net_prefix      = "app"
vm_name         = "httpd"
admin_username  = "<ADMIN_USERNAME>"
admin_password  = "<ADMIN_PASSWORD>"

