apiVersion: v1
kind: Namespace
metadata:
  name: '${namespace}'
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: '${namespace}'
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: flask-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
  name: flask-app
  namespace: '${namespace}'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - image: '<your_docker_user>/flask-app:${trigger[''tag'']}'
          name: flask-app
          ports:
            - containerPort: 5000
