subscription_id = "<SUBSCRIPTION_ID>"
client_id       = "<VALUE_OF_APP_ID>"
client_secret   = "<VALUE_OF_PASSWORD>"
tenant_id       = "<VALUE_OF_TENANT>"
rg_name         = "lamp-rg"
location     = "West Europe"
admin_username  = "ssh_admin"
admin_password  = "Password@1"
